model_id: stabilityai/stable-diffusion-2-1-base
model_dir: ./hf-models
prompt: A cute and realistic kitten
negative_prompt: Oversaturated, blurry, low quality
img_resolution: 512
num_inference_steps: 35
guidance_scale: 8
local_files_only: True
hydra:
  output_subdir: null
  run:
    dir: .
defaults:
  - _self_
  - override hydra/job_logging: disabled
