model_id: stabilityai/stable-diffusion-2-1-base
model_dir: ./hf-models
prompt: A cute and realistic kitten
negative_prompt:
img_resolution: 512
num_inference_steps: 35
output_file: out.png
output_dir: out
guidance_scale: 8
guidance_mode: cfg
seed: 42
local_files_only: True
inversion: False
hydra:
  output_subdir: null
  run:
    dir: .
defaults:
  - _self_
  - override hydra/job_logging: disabled
