model_dir: ./pretrained/hf-models
prompt: ''
guidance_scale: 7.5
hydra:
  output_subdir: null
  run:
    dir: .
defaults:
  - _self_
  - model: sd_xl
  - data: rednet
  - override hydra/job_logging: disabled
